[package]
name = "remote-bin"
version = "0.1.0"
edition = "2021"
authors = ["YdrMaster <ydrml@hotmail.com>"]
readme = "README.md"

[dependencies]
pm1-sdk = { path = "../pm1-sdk-3" }
lidar-faselase = { path = "../lidar-faselase" }
rtk-ins570 = { path = "../rtk-ins570", optional = true }
parry2d = "*"

[features]
default = []
rtk = ["rtk-ins570"]

# 减小二进制体积
[profile.release]
lto = true
codegen-units = 1
panic = 'abort'
# strip -s target/release/...
