[package]
name = "robot-bin"
version = "0.1.0"
edition = "2021"
authors = ["YdrMaster <ydrml@hotmail.com>"]
readme = "README.md"

[dependencies]
pm1-sdk = { path = "../pm1-sdk-3" }
lidar-faselase = { path = "../lidar-faselase" }
rtk-ins570 = { path = "../rtk-ins570" }
pose-filter = { path = "../pose-filter" }
path-tracking = { path = "../path-tracking" }
async-std = { version = "*", features = ["attributes"] }
parry2d = "*"

# 减小二进制体积
[profile.release]
lto = true
codegen-units = 1
panic = 'abort'
# strip -s target/release/...
