[package]
name = "joystick"
version = "0.1.0"
edition = "2021"
authors = ["YdrMaster <ydrml@hotmail.com>"]
readme = "README.md"

[dependencies]
robot-bin = { path = "../../" }
joystick-win = { path = "../../../joystick-win" }
async-std = "*"
